language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
before_install:
  - curl -L https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.9/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR
script:
  - bundle install
  - bundle exec rake test:full
